# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Bernardo Oliveira Pinto'
tagline:          'Team Lead and Dev @ Celfocus'
description:      'The canvas for some of my thoughts'
url:              https://bopinto.github.io
baseurl:          /

author:
  name:           'Bernardo Oliveira Pinto'
  twitter:        https://twitter.com/bopinto
  linkedin:       https://www.linkedin.com/in/bopinto/
  github:         https://www.github.com/bopinto

paginate:         5
